version: '3.9'

services: 
  webserver:
    image: nginx:latest
    container_name: sic_nginx
    volumes:
      - ./default-front.conf:/etc/nginx/conf.d/default.conf
      - ./front:/var/www/html
    network_mode: host
